<?php
/**
 * Created by PhpStorm.
 * User: AndySong
 * Date: 2015-11-13
 * Time: 16:38
 *
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'This username has already been taken.' => '用户名已经被使用。',
    'Register' => '注册',
    'This mobile has already been taken.' => '手机号已经被使用。',
    'Get Verify Code' => '获取验证码',
    'Get Verify SMS Code' => '发送短信验证码',
    'Invalid SMS verify code.' => '短信验证码错误',
    'Confirm Join' => '确认加入',
    'This company has already been taken.' => '该公司已经被注册。',
    'Confirm Reset' => '确认找回',
    'Recovered password successfully.' => '找回密码成功。',
    'Your account has been created.' => '账号注册成功。',
    'Invalid invitation code.' => '错误的邀请码。',
    'Users' => '会员列表',
    'Create User' => '新增会员',
    'Username' => '会员名',
    'Password' => '密码'
];